export const youtubeChannel = 'https://www.youtube.com/@Tech_bhaiyaji';

export const videos = [
  {
    title: 'Latest YouTube Video',
    tag: 'Featured experience',
    url: 'https://youtu.be/0v5ZH7Wnk9Y?si=jInw5aYuJqRfGGlB',
    thumbnailClass: 'featured-hnh',
    description: 'Watch the latest career and job experience vlog on YouTube.',
  },
  {
    title: 'A day in my work life',
    tag: 'Career vlog',
    url: 'https://youtu.be/DPaKtALadyM?si=f5SW9hPdHE1Vn7EU',
    thumbnailClass: 'career-dpa',
    description: 'Explore practical routines and lessons from the workplace.',
  },
  {
    title: 'Real work experience',
    tag: 'Career vlog',
    url: 'https://youtu.be/hnh0QdBsvkY?si=LENmia5gQr1jhn0Q',
    thumbnailClass: 'career-hnh',
    description: 'Find useful guidance before applying or joining.',
  },
];

export const jobs = [
  {
    title: 'Accenture Hiring Non Voice Associate (Email Support)',
    company: 'Accenture',
    category: 'private',
    type: 'Full Time',
    location: 'India',
    experience: 'Freshers (0-1 Years)',
    salary: 'Rs 4-5 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-09-25T12:00:00+05:30',
    details: [
      'Role: Non Voice Associate (Email Support)',
      'Education: Any Graduate',
      'Experience: Freshers (0-1 Years)',
      'Salary: Rs 4-5 LPA (Expected)',
    ],
    url: 'https://www.accenture.com/in-en/careers/jobdetails?id=AIOC-S01665811_en&title=IT+Customer+Service+New+Associate',
  },
  {
    title: 'Deloitte Associate Services Specialist',
    company: 'Deloitte',
    category: 'private',
    type: 'Full Time',
    location: 'India',
    experience: 'Freshers (0-2 Years)',
    salary: 'Rs 4-8 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-09-25T11:00:00+05:30',
    details: [
      'Role: Associate Services Specialist',
      'Education: Any Graduate',
      'Experience: Freshers (0-2 Years)',
      'Salary: Rs 4-8 LPA (Expected)',
    ],
    url: '',
  },
  {
    title: 'GlobalLogic Associate Analyst (Data Collection)',
    company: 'GlobalLogic',
    category: 'private',
    type: 'Full Time',
    location: 'India',
    experience: 'Freshers (0-1 Years)',
    salary: 'Rs 4-6 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-09-25T10:00:00+05:30',
    details: [
      'Role: Associate Analyst (Data Collection)',
      "Education: Any Bachelor's Degree",
      'Experience: Freshers (0-1 Years)',
      'Salary: Rs 4-6 LPA (Expected)',
    ],
    url: 'https://www.globallogic.com/careers/associate-analyst-data-collection-irc304990/',
  },
  {
    title: 'HCL Process Associate - Mega Virtual Drive',
    company: 'HCLTech',
    category: 'bpo',
    type: 'BPO',
    location: 'Virtual Drive',
    experience: 'Freshers',
    salary: 'Rs 3-4 LPA',
    deadline: '26 September 2026',
    postedAt: '2026-09-25T09:00:00+05:30',
    details: [
      'Role: Process Associate',
      'Education: Any Graduate',
      'Experience: Freshers',
      'Salary: Rs 3-4 LPA (Expected)',
      'Drive Date: 26th September 2026',
    ],
    url: 'https://www.naukri.com/job-listings-hcltech-fresher-virtual-drive-on-26th-bpo-domain-voice-process-hcltech-bengaluru-0-to-0-years-240926021157',
  },
  {
    title: 'Deloitte Human Resources Intern',
    company: 'Deloitte',
    category: 'internship',
    type: 'Internship',
    location: 'India',
    experience: 'Freshers',
    salary: 'Rs 4-5 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-09-18T10:30:00+05:30',
    details: [
      'Role: Human Resources Intern',
      'Education: Any Graduate',
      'Experience: Freshers',
      'Salary: Rs 4-5 LPA (Expected)',
    ],
    url: 'https://www.linkedin.com/jobs/view/4463008181/',
  },
  {
    title: 'Cognizant Data Analyst',
    company: 'Cognizant',
    category: 'private',
    type: 'Full Time',
    location: 'Gurugram, India',
    experience: 'Freshers (0-1 Years)',
    salary: 'Rs 4-6 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-09-18T09:30:00+05:30',
    details: [
      'Role: Data Analyst',
      'Education: Any Graduate',
      'Experience: Freshers (0-1 Years)',
      'Salary: Rs 4-6 LPA (Expected)',
    ],
    url: 'https://www.naukri.com/job-listings-analyst-cognizant-gurugram-0-to-1-years-090926019267?src=jobsearchDesk&sid=17891105764605790&xp=1&px=1',
  },
  {
    title: 'Jio Associate',
    company: 'Jio',
    category: 'work-from-home',
    type: 'Full Time',
    location: 'Remote',
    experience: 'Freshers',
    salary: 'Rs 3-5 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-09-18T08:30:00+05:30',
    details: [
      'Role: Associate',
      'Education: Any Graduate',
      'Experience: Freshers',
      'Location: Remote (Multiple)',
      'Salary: Rs 3-5 LPA (Expected)',
    ],
    url: 'https://careers.jio.com/frmfuncwisejob.aspx?func=KXDwg1INMo8=&desc=8GyES+LxTYsY+mFzXdx1Rg==&flag=/wASbQn4xyQ=',
  },
  {
    title: 'Peroptyx Data Analyst',
    company: 'Peroptyx',
    category: 'work-from-home',
    type: 'Full Time',
    location: 'Remote',
    experience: 'Freshers (0-5 Years)',
    salary: 'Rs 4-5 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-09-18T07:30:00+05:30',
    details: [
      'Role: Data Analyst',
      'Education: Any Graduate',
      'Experience: Freshers (0-5 Years)',
      'Location: Remote',
      'Salary: Rs 4-5 LPA (Expected)',
    ],
    url: 'https://www.naukri.com/peroptyx-jobs?k=peroptyx&nignbevent_src=jobsearchDeskGNB&experience=0',
  },
  {
    title: 'Deloitte Freshers Internship',
    company: 'Deloitte',
    category: 'internship',
    type: 'Internship',
    location: 'India',
    experience: 'Freshers',
    salary: 'Rs 4-5 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-09-05T00:00:00+05:30',
    details: [
      'Role: Internship opportunity for freshers',
      'Education: Any Graduate',
      'Experience: Freshers',
      'Salary: Rs 4-5 LPA (Expected)',
    ],
    url: 'https://www.linkedin.com/jobs/view/4453893457/',
  },
  {
    title: 'Amazon ML/GO AI Operations Associate',
    company: 'Amazon',
    category: 'work-from-home',
    type: 'Full Time',
    location: 'Remote',
    experience: 'Freshers/Experienced',
    salary: 'Rs 4-5 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-09-05T00:00:00+05:30',
    details: [
      'Role: ML/GO AI Operations Associate',
      'Education: Any Graduate',
      'Experience: Freshers/Experienced',
      'Location: Remote',
      'Salary: Rs 4-5 LPA (Expected)',
    ],
    url: '',
  },
  {
    title: 'Infosys Data Entry / Banking / Service Desk Roles',
    company: 'Infosys BPM',
    category: 'private',
    type: 'Full Time',
    location: 'Multiple',
    experience: 'Freshers (0-1 Years)',
    salary: 'Rs 3-5 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-08-29T11:30:00+05:30',
    details: [
      'Role: Data Entry, Banking Process, and Service Desk openings',
      'Education: Any Graduate',
      'Experience: Freshers with 0-1 years of experience',
      'Salary: Rs 3-5 LPA (Expected)',
    ],
    url: 'https://www.naukri.com/infosys-bpm-jobs?k=infosys%20bpm&experience=0',
  },
  {
    title: 'JPMC Data Analyst - AML/KYC Operations',
    company: 'JPMorgan Chase & Co.',
    category: 'private',
    type: 'Full Time',
    location: 'India',
    experience: 'fresher-friendly',
    salary: 'Not disclosed',
    deadline: 'Apply soon',
    postedAt: '2026-08-26T14:15:00+05:30',
    details: [
      'Domain: Banking and financial services with AML/KYC operations support',
      'Role: Data analysis, client onboarding, risk review, and compliance checks',
      'Skills: Excel, research, problem solving, reporting, and attention to detail',
    ],
    url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210780424?keyword=Data+Analyst&location=India&locationId=300000000289360&locationLevel=country&mode=location',
  },
  {
    title: 'Fujitsu Junior Data Engineer',
    company: 'Fujitsu',
    category: 'private',
    type: 'Full Time',
    location: 'India',
    experience: 'fresher-friendly',
    salary: 'Rs 4-6 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-08-27T00:00:00+05:30',
    details: [
      'Domain: Data engineering and application development',
      'Role: Junior Data Engineer / Application Development',
      'Experience: Freshers/Experienced',
      "Education: Bachelor's/Master's Degree",
      'Salary: Rs 4-6 LPA (Expected)',
    ],
    url: 'https://www.jobs.global.fujitsu.com/job/Application-Development/10854-en_US',
  },
  {
    title: 'Oracle IT Service Desk - Customer Service Coordinator',
    company: 'Oracle',
    category: 'private',
    type: 'Full Time',
    location: 'India',
    experience: '0-2 Years',
    salary: 'Rs 4-5 LPA',
    deadline: 'Apply soon',
    postedAt: '2026-08-27T00:00:00+05:30',
    details: [
      'Domain: IT services and customer support',
      'Role: IT Service Desk / Customer Service Coordinator',
      'Experience: Freshers (0-2 Years)',
      'Education: Any Graduate',
      'Salary: Rs 4-5 LPA (Expected)',
    ],
    url: 'https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/job/339174?lastSelectedFacet=LOCATIONS&selectedFlexFieldsFacets=%22AttributeChar6%7C0+to+2%2B+years%22&selectedLocationsFacet=300000000106947',
  },
  {
    title: 'ISRO Scientist/Engineer - SC',
    company: 'ISRO',
    category: 'government',
    type: 'Full Time',
    location: 'India',
    experience: 'As per notification',
    salary: 'As per notification',
    deadline: 'Check official notification',
    postedAt: '2026-08-27T00:00:00+05:30',
    details: [
      'Organization: Indian Space Research Organisation (ISRO)',
      'Domain: Space Technology and Research',
      'Role: Scientist/Engineer - SC',
      'Stream: Computer Science / Information Technology related',
      'Eligibility: As per official recruitment notification',
    ],
    url: 'OFFICIAL_EXACT_JOB_URL',
  },
  {
    title: 'ISRO Graduate Apprentice - Computer Science',
    company: 'ISRO / URSC',
    category: 'government',
    type: 'Apprenticeship',
    location: 'Bengaluru, India',
    experience: 'Fresher',
    salary: 'As per apprenticeship norms',
    deadline: '28 August 2026',
    postedAt: '2026-08-27T00:00:00+05:30',
    details: [
      'Organization: U R Rao Satellite Centre (URSC), ISRO',
      'Domain: Space Technology',
      'Role: Graduate Apprentice',
      'Stream: Computer Science / IT related',
      'Last Date: 28 August 2026',
    ],
    url: 'https://apps.ursc.gov.in/URSCBE-2026/advt.jsp',
  },
  {
    title: 'Cognizant Data Analytics Process Executive',
    company: 'Cognizant',
    category: 'private',
    type: 'Full Time',
    location: 'India',
    experience: 'Fresher',
    salary: 'Not disclosed',
    deadline: 'Apply soon',
    postedAt: '2026-08-26T10:30:00+05:30',
    details: ['Qualification: Any graduate or fresher', 'Skills: Excel, reporting, data analytics basics', 'Role: Process Executive'],
    url: youtubeChannel,
  },
  {
    title: 'Customer Support Executive',
    company: 'Company Name',
    category: 'work-from-home',
    type: 'Full Time',
    location: 'Remote / Work from home',
    experience: 'Fresher',
    salary: 'Add expected salary here',
    deadline: 'Apply soon',
    postedAt: '2026-08-26T08:15:00+05:30',
    details: ['Qualification: 12th pass, graduate, or fresher', 'Skills: Communication, email support, basic computer', 'Salary: Add expected salary here'],
    url: youtubeChannel,
  },
  {
    title: 'Social Media Intern',
    company: 'Company Name',
    category: 'private',
    type: 'Internship',
    location: 'Delhi / Hybrid',
    experience: 'Student / Fresher',
    salary: 'Stipend expected',
    deadline: 'Add application deadline',
    postedAt: '2026-08-25T18:45:00+05:30',
    details: ['Qualification: Student, fresher, or career starter', 'Skills: Instagram, Canva, basic editing', 'Last date: Add application deadline'],
    url: youtubeChannel,
  },
  {
    title: 'Government IT Job Alert for Freshers',
    company: 'Department Name',
    category: 'government',
    type: 'Government',
    location: 'India',
    experience: 'Fresher',
    salary: 'As per notification',
    deadline: 'Add application deadline',
    postedAt: '2026-08-25T12:00:00+05:30',
    details: ['Qualification: Add official eligibility here', 'Age limit: Add details here', 'Last date: Add application deadline'],
    url: youtubeChannel,
  },
  {
    title: 'BPO Support Associate',
    company: 'Hiring Partner',
    category: 'bpo',
    type: 'BPO',
    location: 'Noida / Gurugram',
    experience: 'Fresher',
    salary: 'Not disclosed',
    deadline: 'Apply soon',
    postedAt: '2026-08-24T20:30:00+05:30',
    details: ['Qualification: 12th pass or graduate', 'Skills: Voice process, customer handling', 'Shift: Rotational'],
    url: youtubeChannel,
  },
];

export const categoryLabels = {
  private: 'Private Jobs',
  government: 'Government Tech Jobs',
  'work-from-home': 'Work From Home Jobs',
  internship: 'Internships',
  bpo: 'BPO Jobs',
};
